import Joi, { ObjectSchema } from 'joi';
export const validationSchema: ObjectSchema<any> = Joi.object({
    PORT: Joi.number().default(3000),
    API_PREFIX: Joi.string().default('API-PREFIX'),
    CONTEXT: Joi.string().default('api'),
    CORS_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
    CORS_CREDENTIALS: Joi.boolean().truthy('true').falsy('false').default(false),
    ORIGINS: Joi.string().default('*'),
    ALLOWED_HEADERS: Joi.string().default('Content-Type, Authorization'),
    ALLOWED_METHODS: Joi.string().default('GET, POST, PUT, DELETE'),
    SWAGGER_PATH: Joi.string().default('docs'),
    SWAGGER_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
    DATABASE_HOST: Joi.string().hostname().default('localhost'),
    DATABASE_PORT: Joi.number().port().default(5432),
    DATABASE_NAME: Joi.string().required(),
    DATABASE_USER: Joi.string().required(),
    DATABASE_PASSWORD: Joi.string().required(),
    JWT_ACCESS_SECRET: Joi.string().min(16).default('change-me-access-secret'),
    JWT_REFRESH_SECRET: Joi.string().min(16).default('change-me-refresh-secret'),
    JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
    JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
});